on:
  release:
    types:
      - published

name: Upload Odin Update

jobs:
  pypi-publish:
    name: Upload Odin Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/odin-vision
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instal the distribution builder
        run: python -m pip install -U build

      - name: Build the distribution packages
        run: python -m build

      - name: Store the distribution packages  
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
